In [18]:
pltfile = 'rch900.6'

hbnfile = 'rch.hbn'
hdffile_1 = 'rch.h5'

wdmfile = 'test10.wdm'
hdffile_2 = 'test10.h5'

from pandas import read_hdf

## Read a PLTGEN File

In [2]:
from readPLTGEN import readPLTGEN

In [3]:
df1 = readPLTGEN(pltfile)
df1.describe()

       FLOW (ft3/s)  ROVOL (acft/dy)  SSED (mg/L)  ROSED (ton/dy)     TEMP (F)
count   4383.000000      4383.000000  4383.000000     4383.000000  4383.000000
mean     584.098201      1158.541892    19.606722       70.587088    46.474319
std      628.446693      1246.505834    31.759704      203.729072    13.872723
min       45.839310        90.920940     4.017808        0.748872    32.072070
25%      206.126950       408.846950     4.431079        1.568601    32.530215
50%      375.030700       743.862500     5.525188        3.091219    42.849880
75%      697.723550      1383.914500    20.494890       35.213100    60.780895
max     5863.976000     11631.020000   450.496600     3455.092000    75.870480

## Read an HBN File

In [4]:
from readHBN import read_HBN

In [5]:
read_HBN(hbnfile, hdffile_1)

In [6]:
df = read_hdf('rch.h5', 'RESULTS_Daily/RCHRES/HYDR/R001')
df.describe()

,VOL,DEP,STAGE,AVDEP,TWID,HRAD,SAREA,AVVEL,AVSECT,USTAR,TAU,RO,IVOL,PRSUPY,VOLEV,ROVOL,POTEV
count,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.000000,9862.0,9862.000000,9862.000000,9862.000000
mean,7.178884,0.835161,0.835161,0.124735,43.935169,0.123665,40.127445,0.867343,7.860070,0.109898,0.024307,10.145023,20.378374,0.0,0.451087,19.947575,0.137253
std,14.736006,0.202017,0.202017,0.060790,42.264832,0.060778,38.601883,0.372530,16.134310,0.021577,0.011946,28.853083,46.977470,0.0,0.571147,44.942234,0.108617
min,0.297173,0.544345,0.544345,0.087073,3.180981,0.084451,2.905296,0.119241,0.325372,0.092551,0.016599,0.038798,0.088007,0.0,-0.002404,0.088403,-0.001522
25%,1.425331,0.709438,0.709438,0.094391,14.667670,0.093494,13.396472,0.490937,1.560582,0.097381,0.018377,0.766148,1.635554,0.0,0.059830,1.617600,0.034331
50%,2.519017,0.778030,0.778030,0.103898,29.758862,0.102672,27.179759,0.895582,2.758048,0.102048,0.020181,2.470057,4.698834,0.0,0.258913,5.011028,0.118188
75%,6.512611,0.905202,0.905202,0.123498,57.738495,0.122972,52.734489,1.218956,7.130596,0.111682,0.024171,8.691883,17.648616,0.0,0.612639,18.215296,0.225191
max,399.510559,2.865203,2.865203,1.355222,322.766541,1.343936,294.793427,2.934510,437.420349,0.369206,0.264160,1283.614258,1229.896240,0.0,4.792470,1127.020142,0.539908

## Read a WDM File

In [22]:
from readWDM import read_WDM

In [23]:
read_WDM(wdmfile, hdffile_2)

In [24]:
df1 = read_hdf(hdffile_2, 'TIMESERIES/TS113')
df1.describe()

count     366.000000
mean      599.021851
std      1049.336792
min        18.000000
25%        70.000000
50%       120.000000
75%       806.000000
max      7920.000000
dtype: float64